import { type Config } from "tailwindcss";
import { fontFamily } from "tailwindcss/defaultTheme";

export default {
  content: [
    "./src/**/*.tsx",
    "./src/**/*.ts",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-geist-sans)", ...fontFamily.sans],
      },
    },
  },
  darkMode: "class",
  plugins: [
    require("@tailwindcss/typography"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
    require('daisyui')
  ],
  daisyui: {
    themes: [
      {
        msparp: {
          "primary": "#0072bc",
          "primary-content": "#9ed9ff",
          "secondary": "#4ade80",
          "secondary-content": "#166534",
          "accent": "#67e8f9",
          "accent-content": "#155e75",
          "neutral": "#4b5563",
          "neutral-content": "#9ca3af",
          "base-100": "#aaaaaa",
          "base-200": "#eeeeee",
          "base-300": "#ececec",
          "base-content": "#232323",
          "info": "#67e8f9",
          "info-content": "#0e7490",
          "success": "#bef264",
          "success-content": "#4d7c0f",
          "warning": "#fcd34d",
          "warning-content": "#b45309",
          "error": "#fda4af",
          "error-content": "#9f1239",
        },
        msdark: {
          "primary": "#38bdf8",
          "primary-content": "#075985",
          "secondary": "#14b8a6",
          "secondary-content": "#0f766e",
          "accent": "#06b6d4",
          "accent-content": "#155e75",
          "neutral": "#6b7280",
          "neutral-content": "#d1d5db",
          "base-100": "#535353",
          "base-200": "#474747",
          "base-300": "#3b3b3b",
          "base-content": "#dadada",
          "info": "#0891b2",
          "info-content": "#cffafe",
          "success": "#15803d",
          "success-content": "#a7f3d0",
          "warning": "#ca8a04",
          "warning-content": "#fef08a",
          "error": "#be123c",
          "error-content": "#fecdd3",
        }
      },
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  }
} satisfies Config;
