import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getCurrentSession } from "@/lib/server/lucia";
import "./globals.css";
import LogoutButton from "../_components/client/LogoutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await getCurrentSession();
  
  return (
    <html lang="en" className="overflow-y-auto h-full m-auto p-0" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full bg-zinc-600 text-black font-bold font-mono overflow-auto m-auto p-0`}
      >
        <div id="container" className="bg-zinc-300 box-border w-[98%] max-w-[1500px] relative min-h-[94%] overflow-hidden p-5 rounded-xl">
          <div className="logo float-none p-0 m-0">
            <div className="image">
              <a href="/">
                <img
                  src="/img/spacer.gif"
                  alt="Logo"
                />
              </a>
            </div>
          </div>
          <div id="charbar"></div>
          <nav id="nav">
            <li>
              <a href="/rules" target="_blank">Rules</a>
            </li>
            <li>
              <a href="/chats">Groups</a>
            </li>
            <li>
              <a href="https://www.etsy.com/ca/shop/HSRPUniverseMerch" target="_blank">Merch</a>
            </li>
            {user !== null && (
              <li className="float-right">
                <LogoutButton/>
              </li>
            )}
            {user === null && (
              <>
              <li className="float-right">
                <a href="/login">Login</a>
              </li>
              <li className="float-right">
                <a href="/register">Register</a>
              </li>
              </>
            )}
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
